### Heroes Of Pymoli Data Analysis
* Of the 1163 active players, the vast majority are male (84%). There also exists, a smaller, but notable proportion of female players (14%).

* Our peak age demographic falls between 20-24 (44.8%) with secondary groups falling between 15-19 (18.60%) and 25-29 (13.4%).  
-----

### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np

# File to Load (Remember to Change These)
file_to_load = "Resources/purchase_data.csv"

# Read Purchasing File and store into Pandas data frame
purchase_data = pd.read_csv(file_to_load)
purchase_data.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44

In [2]:
#check types
purchase_data.dtypes

Purchase ID      int64
SN              object
Age              int64
Gender          object
Item ID          int64
Item Name       object
Price          float64
dtype: object

## Player Count

* Display the total number of players

In [3]:
# number of players
players = purchase_data["SN"].unique()
len(players)

576

## Purchasing Analysis (Total)

* Run basic calculations to obtain number of unique items, average price, etc.


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [4]:
# number of unique items
unique = purchase_data["Item Name"].unique()
len(unique)

179

In [5]:
# average purchase price
avg_price = purchase_data["Price"].mean()
print(avg_price)

3.050987179487176

In [6]:
# number of purchases
ID = purchase_data["Purchase ID"].unique()
len(ID)

780

In [7]:
# total revenue
rev = purchase_data["Price"].sum()
print(rev)

2379.77

In [8]:
# summary dataframe
summary = pd.DataFrame({"Unique Items":[len(unique)], "Average Purchase Price":[avg_price],
                                        "Total Number of Purchases":[len(ID)],"Total Revenue":[rev]})
summary["Unique Items"] = summary["Unique Items"].map("{} Items".format)
summary["Average Purchase Price"] = summary["Average Purchase Price"].map("${:.2f}".format)
summary["Total Number of Purchases"] = summary["Total Number of Purchases"].map("{} Purchases".format)
summary["Total Revenue"] = summary["Total Revenue"].map("${:,}".format)

summary

  Unique Items Average Purchase Price Total Number of Purchases Total Revenue
0    179 Items                  $3.05             780 Purchases     $2,379.77

## Gender Demographics

* Percentage and Count of Male Players


* Percentage and Count of Female Players


* Percentage and Count of Other / Non-Disclosed

In [9]:
#Get Percentage of genders and format

percentage = purchase_data["Gender"].value_counts()/purchase_data["Gender"].count()*100
percentage2 = percentage.map("{:.2f}%".format)
# count genders
count = purchase_data["Gender"].value_counts()
count = count.rename_axis('Gender').reset_index(name='counts')
count
percentage2 = percentage2.rename_axis('Gender').reset_index(name='counts')
percentage2
# put percentage and count on table
new = pd.merge(percentage2,count,on="Gender")
new = new.rename(index=str,columns={"counts_x":"Percentage","counts_y":"Count"})
new
# how do i make the genders go on each row?

                  Gender Percentage  Count
0                   Male     83.59%    652
1                 Female     14.49%    113
2  Other / Non-Disclosed      1.92%     15


## Purchasing Analysis (Gender)

* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. by gender




* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [10]:
# created requested variables and group by gender
gender = purchase_data.groupby(["Gender"])
gender_price = gender["Price"].mean()
gender_count = gender["Purchase ID"].count()
gender_total = gender["Price"].sum()
# only show unique SN's
uniqueusers = purchase_data.drop_duplicates(subset="SN",keep="first")
# group unique users by gender
groupsn = uniqueusers.groupby(["Gender"])
# get purchase per person by dividing total price (grouped by gender) / unique users (grouped by gender)
purchase_per_person = gender_total/groupsn["SN"].count()

# compile into dataframe
summary_data2=pd.DataFrame({"Purchase Count":gender_count,"Average Purchase Price":gender_price,"Total Purchases":gender_total,"Purchase Per Person":purchase_per_person})

#format
summary_data2["Average Purchase Price"] = summary_data2["Average Purchase Price"].map("${:.2f}".format)
summary_data2["Total Purchases"] = summary_data2["Total Purchases"].map("${:.2f}".format)
summary_data2["Purchase Per Person"] = summary_data2["Purchase Per Person"].map("${:.2f}".format)
summary_data2

,Purchase Count,Average Purchase Price,Total Purchases,Purchase Per Person
Gender,,,,
Female,113,$3.20,$361.94,$4.47
Male,652,$3.02,$1967.64,$4.07
Other / Non-Disclosed,15,$3.35,$50.19,$4.56

## Age Demographics

* Establish bins for ages


* Categorize the existing players using the age bins. Hint: use pd.cut()


* Calculate the numbers and percentages by age group


* Create a summary data frame to hold the results


* Optional: round the percentage column to two decimal points


* Display Age Demographics Table

In [11]:
age = purchase_data["Age"].value_counts().sort_index()
age
#sort by 5
bins = [0,5,10,15,20,25,30,35,40,45,50]
group_names = ["1-5","6-10","11-15","16-20","21-25","26-30","31-35","36-40","41-45","46-50"]
purchase_data["Age Summary"] = pd.cut(purchase_data["Age"],bins,labels=group_names)
new_purchase_data = purchase_data.groupby(["Age Summary"])
summary = new_purchase_data.count()/780*100
summary

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
Age Summary,,,,,,,
1-5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6-10,4.102564,4.102564,4.102564,4.102564,4.102564,4.102564,4.102564
11-15,6.923077,6.923077,6.923077,6.923077,6.923077,6.923077,6.923077
16-20,25.641026,25.641026,25.641026,25.641026,25.641026,25.641026,25.641026
21-25,41.666667,41.666667,41.666667,41.666667,41.666667,41.666667,41.666667
26-30,9.871795,9.871795,9.871795,9.871795,9.871795,9.871795,9.871795
31-35,6.666667,6.666667,6.666667,6.666667,6.666667,6.666667,6.666667
36-40,4.230769,4.230769,4.230769,4.230769,4.230769,4.230769,4.230769
41-45,0.897436,0.897436,0.897436,0.897436,0.897436,0.897436,0.897436
46-50,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

## Purchasing Analysis (Age)

* Bin the purchase_data data frame by age


* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. in the table below


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [12]:
new_purchase_data = purchase_data.groupby(["Age Summary"])
new_price = new_purchase_data["Price"].mean()
new_count = new_purchase_data["Purchase ID"].count()
new_total = new_purchase_data["Price"].sum()
unique = purchase_data.drop_duplicates(subset="SN",keep="first")
groupsn = unique.groupby(["Age Summary"])
# get purchase per person by dividing total price (grouped by gender) / unique users (grouped by gender)
purchase_per_person = new_total/groupsn["Age Summary"].count()
summary_data3=pd.DataFrame({"Purchase Count":new_count,"Average Purchase Price":new_price,"Total Purchases":new_total,"Purchase Per Person":purchase_per_person})

summary_data3["Average Purchase Price"] = summary_data3["Average Purchase Price"].map("${:.2f}".format)
summary_data3["Total Purchases"] = summary_data3["Total Purchases"].map("${:.2f}".format)
summary_data3["Purchase Per Person"] = summary_data3["Purchase Per Person"].map("${:.2f}".format)

summary_data3

,Purchase Count,Average Purchase Price,Total Purchases,Purchase Per Person
Age Summary,,,,
1-5,0,$nan,$0.00,$nan
6-10,32,$3.40,$108.96,$4.54
11-15,54,$2.90,$156.60,$3.82
16-20,200,$3.11,$621.56,$4.14
21-25,325,$3.02,$981.64,$4.23
26-30,77,$2.88,$221.42,$3.75
31-35,52,$2.99,$155.71,$4.21
36-40,33,$3.40,$112.35,$4.32
41-45,7,$3.08,$21.53,$3.08
46-50,0,$nan,$0.00,$nan

## Top Spenders

* Run basic calculations to obtain the results in the table below


* Create a summary data frame to hold the results


* Sort the total purchase value column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [13]:
uniquesn = purchase_data.drop_duplicates(subset="SN",keep="first")
groupsn = uniquesn.groupby(["SN"])
new_price2 = groupsn["Price"].mean()
new_count2 = groupsn["Purchase ID"].count()
new_total2 = groupsn["Price"].sum()
summary_data4 = pd.DataFrame({"Purchase Count":new_count2,"Average Purchase Price":new_price2,"Total Purchases":new_total2})
test = summary_data4.sort_values(['Total Purchases'],ascending=False)
test

                Purchase Count  Average Purchase Price  Total Purchases
SN
Dyally87                     1                    4.99             4.99
Hiasri33                     1                    4.99             4.99
Chanirrasta87                1                    4.94             4.94
Yarithsurgue62               1                    4.94             4.94
Lirtilsa71                   1                    4.94             4.94
Lassilsala30                 1                    4.94             4.94
Ririp86                      1                    4.94             4.94
Strithenu87                  1                    4.93             4.93
Smaistysu35                  1                    4.93             4.93
Chadjask77                   1                    4.93             4.93
Mindossa76                   1                    4.93             4.93
Idastidru52                  1                    4.93             4.93
Firan91                      1                    4.91             4.91
Aerithnuphos61               1                    4.91             4.91
Aeda94                       1                    4.91             4.91
Filurarn35                   1                    4.91             4.91
Aerithllora36                1                    4.90             4.90
Lirtastsda29                 1                    4.90             4.90
Phistym51                    1                    4.90             4.90
Meosridil82                  1                    4.90             4.90
Reunasu60                    1                    4.90             4.90
Assilsan72                   1                    4.90             4.90
Laedallo55                   1                    4.90             4.90
Sundadar27                   1                    4.89             4.89
Halaecal66                   1                    4.89             4.89
Ennalmol65                   1                    4.88             4.88
Ithergue48                   1                    4.88             4.88
Tyaelo67                     1                    4.88             4.88
Lisilsa62                    1                    4.88             4.88
Irithlis29                   1                    4.86             4.86
...                        ...                     ...              ...
Hirirap39                    1                    1.16             1.16
Jiskimsda56                  1                    1.14             1.14
Ilista82                     1                    1.14             1.14
Aisur51                      1                    1.14             1.14
Tyarithn67                   1                    1.14             1.14
Iduelis31                    1                    1.10             1.10
Yasur85                      1                    1.10             1.10
Aillyriadru65                1                    1.10             1.10
Undjask33                    1                    1.10             1.10
Eryon48                      1                    1.10             1.10
Aelidru27                    1                    1.09             1.09
Lirtassa52                   1                    1.09             1.09
Yalaeria91                   1                    1.06             1.06
Saida58                      1                    1.03             1.03
Aesurstilis64                1                    1.03             1.03
Euthe35                      1                    1.03             1.03
Hala31                       1                    1.02             1.02
Pheodaisun84                 1                    1.02             1.02
Eudanu84                     1                    1.02             1.02
Isurria36                    1                    1.02             1.02
Ililsasya43                  1                    1.02             1.02
Qilalista41                  1                    1.02             1.02
Eodailis27                   1                    1.02             1.02
Aina42                       1                    1.02             1.02
Irilis75                     1                    1.02             1.02
Frichjaskan98                1                    1.02             1.02
Aidai61                      1                    1.01             1.01
Chanirra79                   1                    1.01             1.01
Eusurdeu49                   1                    1.01             1.01
Alo38                        1                    1.00             1.00

[576 rows x 3 columns]

## Most Popular Items

* Retrieve the Item ID, Item Name, and Item Price columns


* Group by Item ID and Item Name. Perform calculations to obtain purchase count, item price, and total purchase value


* Create a summary data frame to hold the results


* Sort the purchase count column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [63]:
newgroup = purchase_data.groupby(['Item ID','Item Name'])
summary6 = pd.DataFrame({"Count": newgroup["Item Name"].count(),"Price": newgroup["Price"].mean(),"Total Price":newgroup["Price"].sum()})
test = summary6.sort_values(['Count'],ascending=False)
test

,,Count,Price,Total Price
Item ID,Item Name,,,
178,"Oathbreaker, Last Hope of the Breaking Storm",12,4.23,50.76
145,Fiery Glass Crusader,9,4.58,41.22
108,"Extraction, Quickblade Of Trembling Hands",9,3.53,31.77
82,Nirvana,9,4.90,44.10
19,"Pursuit, Cudgel of Necromancy",8,1.02,8.16
103,Singed Scalpel,8,4.35,34.80
75,Brutality Ivory Warmace,8,2.42,19.36
72,Winter's Bite,8,3.77,30.16
60,Wolf,8,3.54,28.32
59,"Lightning, Etcher of the King",8,4.23,33.84
37,"Shadow Strike, Glory of Ending Hope",8,3.16,25.28
34,Retribution Axe,8,2.22,17.76
92,Final Critic,8,4.88,39.04
53,Vengeance Cleaver,7,2.05,14.35
110,Suspension,7,1.44,10.08
7,"Thorn, Satchel of Dark Souls",7,1.33,9.31
71,Demise,7,1.61,11.27
117,"Heartstriker, Legacy of the Light",7,1.79,12.53
159,"Oathbreaker, Spellblade of Trials",7,3.08,21.56
85,Malificent Bag,7,1.75,12.25
164,Exiled Doomblade,7,1.63,11.41
141,Persuasion,7,3.19,22.33
78,"Glimmer, Ender of the Moon",7,4.40,30.80
102,Avenger,6,3.44,20.64
129,"Fate, Vengeance of Eternal Justice",6,1.54,9.24
93,Apocalyptic Battlescythe,6,1.97,11.82
54,Eternal Cleaver,6,2.50,15.00
3,Phantomlight,6,2.49,14.94
2,Verdict,6,2.48,14.88
40,Second Chance,6,2.52,15.12
...,...,...,...,...
81,Dreamkiss,2,3.61,7.22
6,Rusty Skull,2,3.70,7.40
18,"Torchlight, Bond of Storms",2,4.65,9.30
26,Unholy Wand,2,1.12,2.24
28,"Flux, Destroyer of Due Diligence",2,1.06,2.12
30,Stormcaller,2,2.21,4.42
158,"Darkheart, Butcher of the Champion",2,2.45,4.90
69,"Frenzy, Defender of the Harvest",2,1.98,3.96
132,Persuasion,2,3.33,6.66
63,Stormfury Mace,2,4.99,9.98
56,Foul Titanium Battle Axe,2,2.92,5.84
127,"Heartseeker, Reaver of Souls",2,3.92,7.84
48,"Rage, Legacy of the Lone Victor",2,2.48,4.96
125,Whistling Mithril Warblade,2,1.00,2.00
43,Foul Edge,2,3.54,7.08
115,Spectral Diamond Doomblade,2,2.04,4.08
33,Curved Axe,2,1.16,2.32
31,Trickster,2,1.55,3.10
118,"Ghost Reaver, Longsword of Magic",1,2.17,2.17
47,"Alpha, Reach of Ending Hope",1,3.58,3.58
42,The Decapitator,1,1.75,1.75
27,"Riddle, Tribute of Ended Dreams",1,3.30,3.30
126,Exiled Mithril Longsword,1,2.00,2.00
51,Endbringer,1,4.66,4.66
90,Betrayer,1,2.94,2.94
104,Gladiator's Glaive,1,1.93,1.93
23,Crucifer,1,1.99,1.99
180,Stormcaller,1,3.36,3.36
91,Celeste,1,4.17,4.17
134,Undead Crusader,1,4.50,4.50

## Most Profitable Items

* Sort the above table by total purchase value in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the data frame

In [64]:
newgroup = purchase_data.groupby(['Item ID','Item Name'])
summary6 = pd.DataFrame({"Count": newgroup["Item Name"].count(),"Price": newgroup["Price"].mean(),"Total Price":newgroup["Price"].sum()})
test = summary6.sort_values(['Total Price'],ascending=False)
test

,,Count,Price,Total Price
Item ID,Item Name,,,
178,"Oathbreaker, Last Hope of the Breaking Storm",12,4.23,50.76
82,Nirvana,9,4.90,44.10
145,Fiery Glass Crusader,9,4.58,41.22
92,Final Critic,8,4.88,39.04
103,Singed Scalpel,8,4.35,34.80
59,"Lightning, Etcher of the King",8,4.23,33.84
108,"Extraction, Quickblade Of Trembling Hands",9,3.53,31.77
78,"Glimmer, Ender of the Moon",7,4.40,30.80
72,Winter's Bite,8,3.77,30.16
60,Wolf,8,3.54,28.32
179,"Wolf, Promise of the Moonwalker",6,4.48,26.88
160,Azurewrath,6,4.40,26.40
25,Hero Cane,6,4.35,26.10
37,"Shadow Strike, Glory of Ending Hope",8,3.16,25.28
139,"Mercy, Katana of Dismay",5,4.94,24.70
128,"Blazeguard, Reach of Eternity",5,4.91,24.55
138,"Peacekeeper, Wit of Dark Magic",5,4.74,23.70
141,Persuasion,7,3.19,22.33
87,"Deluge, Edge of the West",5,4.43,22.15
159,"Oathbreaker, Spellblade of Trials",7,3.08,21.56
136,Ghastly Adamantite Protector,6,3.58,21.48
65,Conqueror Adamantite Mace,5,4.24,21.20
101,Final Critic,5,4.19,20.95
102,Avenger,6,3.44,20.64
133,Faith's Scimitar,5,4.09,20.45
39,"Betrayal, Whisper of Grieving Widows",5,3.94,19.70
111,Misery's End,4,4.89,19.56
165,Bone Crushing Silver Skewer,4,4.86,19.44
75,Brutality Ivory Warmace,8,2.42,19.36
52,Hatred,4,4.84,19.36
...,...,...,...,...
124,Venom Claymore,4,1.29,5.16
0,Splinter,4,1.28,5.12
155,War-Forged Gold Deflector,5,1.01,5.05
48,"Rage, Legacy of the Lone Victor",2,2.48,4.96
158,"Darkheart, Butcher of the Champion",2,2.45,4.90
51,Endbringer,1,4.66,4.66
134,Undead Crusader,1,4.50,4.50
30,Stormcaller,2,2.21,4.42
135,Warped Diamond Crusader,3,1.40,4.20
91,Celeste,1,4.17,4.17
177,"Winterthorn, Defender of Shifting Worlds",2,2.08,4.16
70,Hope's End,4,1.03,4.12
115,Spectral Diamond Doomblade,2,2.04,4.08
69,"Frenzy, Defender of the Harvest",2,1.98,3.96
47,"Alpha, Reach of Ending Hope",1,3.58,3.58
180,Stormcaller,1,3.36,3.36
27,"Riddle, Tribute of Ended Dreams",1,3.30,3.30
183,Dragon's Greatsword,3,1.09,3.27
31,Trickster,2,1.55,3.10
168,"Sun Strike, Jaws of Twisted Visions",2,1.48,2.96
90,Betrayer,1,2.94,2.94
33,Curved Axe,2,1.16,2.32
26,Unholy Wand,2,1.12,2.24
118,"Ghost Reaver, Longsword of Magic",1,2.17,2.17
28,"Flux, Destroyer of Due Diligence",2,1.06,2.12
125,Whistling Mithril Warblade,2,1.00,2.00
126,Exiled Mithril Longsword,1,2.00,2.00
23,Crucifer,1,1.99,1.99
104,Gladiator's Glaive,1,1.93,1.93
42,The Decapitator,1,1.75,1.75